services:
  backend:
    image: bloglist-backend
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    container_name: bloglist-backend
  app:
    image: bloglist-frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    container_name: bloglist-frontend
    depends_on:
      - backend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bloglist-reverse-proxy
    depends_on:
      - app
  debug-helper:
    image: busybox
