services:
  backend:
    image: todo-backend
    ports:
      - "3000:3000"
    build:
      context: ./todo-backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app
    container_name: todo-backend
  app:
    image: todo-frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
    build:
      context: ./todo-frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app
    container_name: todo-frontend
    depends_on:
      - backend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
  debug-helper:
    image: busybox
